### ISSUE TITLE
Duplicate copy of SignPainter.ttc

### ISSUE THREAD

**Issue by ryandesign** [OneGeekArmy/Disk-Jockey-Community#10]
The Disk Jockey 2.5 application contains two copies of the font SignPainter.ttc: one in Contents/Resources and another in Contents/Resources/Fonts.

**Comment by OneGeekArmy** [comment]
Indeed. Thanks for pointing it out.
Future versions of Disk Jockey will no longer rely on additional fonts so I will close this issue.
