### ISSUE TITLE
Legality of distributing SignPainter.ttc

### ISSUE THREAD

**Issue by ryandesign** [OneGeekArmy/Disk-Jockey-Community#11]
Disk Jockey 2.5 contains the font SignPainter.ttc. Is it ok to be distributing this font? As far as I can tell it is part of a commercial font package:

https://housefonts.com/hi/signpainter

It is also bundled with macOS Monterey, at least, presumably due to some special arrangement between Apple and the publisher. If it is bundled with every version of macOS that Disk Jockey is compatible with, then you could use Apple's copy and not risk shipping your own. Or you could include a bitmap or vector of just the text you are using in the app. Or, perhaps a different font that is bundled with all relevant macOS versions could be used, or you could include and use a font available under a free license.

**Comment by OneGeekArmy** [comment]
Future versions of Disk Jockey will no longer rely on additional fonts so I will close this issue.
