### ISSUE TITLE
Images over 10gb?

### ISSUE THREAD

**Issue by clickysteve** [OneGeekArmy/Disk-Jockey-Community#12]
Hello! 

I am trying to use Disk Jockey to create empty hard disk images for an old Akai sampler - an Akai S6000, using ZuluSCSI. 

I've got it to work with disk images created by Disk Jockey of 10,000mb, but that's where DJ tops out. Is it possible to create images larger than that? I want to make the most of the 7 device SCSI limit, and get larger separate disks where I can.

Thanks in advance!

**Comment by OneGeekArmy** [comment]
The limit in place in Disk Jockey is artificial and exists to protect users against issues such as "And suddenly their hard drive now contained a gigantic disk image that filled up everything and there was much sadness".

I've received several requests like this one and I'm contemplating adding a checkbox that pretty much says "I know what I'm doing, let me put in any size I want". I'll try and include it in the next release.

Could you let me know which version of DJ you're using (Windows or macOS)?

**Comment by clickysteve** [comment]
Hey, thank you! I am using the latest version of MacOS. 

> "And suddenly their hard drive now contained a gigantic disk image that filled up everything and there was much sadness".

Having a 'reasonable' limit might also help. e.g. 256gb or something? If not, a disclaimer/checkbox would be great. This would let me utilise the space on my old Akai sampler much better!

**Comment by OneGeekArmy** [comment]
> Edit: It's worth saying that DJ is the only app I've found on newer versions of OSX that can create these type of images, which is wild. Love the disk analyser function as well. Really helpful. Thanks a lot!

You're welcome :) Glad you like it.

Also: check your e-mail. I've sent you a gift.

**Comment by Grieverheart** [comment]
Just wanted to add that I'd also like for the limit to be increased.

**Comment by OneGeekArmy** [comment]
> Just wanted to add that I'd also like for the limit to be increased.

Stay tuned! I'm almost done with a new version of Disk Jockey for macOS that lifts the limit. And it does a ton more stuff too :)

**Comment by macpato82** [comment]
This is good news im also looking forward to the limit being removed

**Comment by Benedict-1966** [comment]
Hi JM,

Hope all is well. May we expect the over 10GB image size implementation any time soon. I don't see the option yet on DJ.

And while I'm here, do you have any BlueSCSI v2 available? I live in Belgium and thinking of buying one for my 2nd Yamaha AW4416 mixer/HD recorder (which I don't have as yet though).

Regards,
Ben

**Comment by OneGeekArmy** [comment]
Hi,

Thanks for writing!

Regarding your Disk Jockey question, a beta of the macOS version of DJ is out and it supports very large images. You can grab it using the links here:
[https://tinkerdifferent.com/threads/disk-jockey-a-disk-image-file-maker-for-your-retro-stuff-beta-for-version-3.1039/](https://tinkerdifferent.com/threads/disk-jockey-a-disk-image-file-maker-for-your-retro-stuff-beta-for-version-3.1039/)

The final version is almost finished but the beta should be stable enough to do what you want.

And I have BlueSCSI v2 available indeed:
[https://shop.onegeekarmy.eu](https://shop.onegeekarmy.eu)

It's great you’re planning on using one in a Yamaha mixer. As you’ll notice in the beta, I’m expanding DJ to start supporting things beyond the Macintosh, and this includes Akai samplers. If you ever get around to it, I’d love to see what a working Yamaha disk image looks like, so I can teach DJ how to create them hassle-free too :)

Hope this helps,
JM

**Comment by Benedict-1966** [comment]
Hi JM,Wonderful. Thanks for the link. That was very quick.The AW4416 mixer/HD multitrack recorder uses a proprietary file system on both the internal and externally connected hard drives, but the external hard drive can also be formatted to FAT16 file system using the AW4416 machine. The internal HD is PATA IDE. The external drives must be SCSI compatible. There is also a CD bay at its front which houses a SCSI (AW4416) or an IDE (AW4416A) CD/CD-R/CD-RW drive. Mines is SCSI so I have replaced the CD drive with a BlueSCSI v2 SD adapter. A mixed situation which can make things complicated to explain and I’m no expert.I see when I have formatted and used a SCSI image with my AW4416 the Apple partition table and the driver and even the HFS volume are still there when I analyse the image with Disk-O-Matic. There are a few who have succeeded in finding out how the AW4416(A) proprietary file system is structured. The developers of AWextract (abandoned), Aware (abandoned), and more recently AWMiner (Ben E. Badman).The external hard drives may also be formatted to a FAT16 file system with the AW4416(A) if one wishes to access the drive with a PC to use the words in the AW4416(A) manual. I am able to format the DJ images with FAT16 via BlueSCSI v2 using my AW4416 but the machine fails using them so I’m stuck with the proprietary file system no other system can read except for a few apps like the ones I mentioned above.I can create 2 images of say 900 MB using DJ and then format them using my AW4416. One in Yamaha’s proprietary file system and one in FAT16. Is that what you need?Best regards,BenedictVerstuurd vanaf mijn iPhoneOp 27 jan 2024 om 13:56 heeft Jean-Michel Durand ***@***.***> het volgende geschreven:﻿
Hi,
Thanks for writing!
Regarding your Disk Jockey question, a beta of the macOS version of DJ is out and it supports very large images. You can grab it using the links here:
https://tinkerdifferent.com/threads/disk-jockey-a-disk-image-file-maker-for-your-retro-stuff-beta-for-version-3.1039/
The final version is almost finished but the beta should be stable enough to do what you want.
And I have BlueSCSI v2 available indeed:
https://shop.onegeekarmy.eu
It's great you’re planning on using one in a Yamaha mixer. As you’ll notice in the beta, I’m expanding DJ to start supporting things beyond the Macintosh, and this includes Akai samplers. If you ever get around to it, I’d love to see what a working Yamaha disk image looks like, so I can teach DJ how to create them hassle-free too :)
Hope this helps,
JM

**Comment by Benedict-1966** [comment]
Super!

**Comment by Benedict-1966** [comment]
Hi JM,

I will send you a 2GB image I created with Disk Jockey (Beta v3) using the
'Other' option.

Regards,
Benedict

Op za 27 jan 2024 om 13:56 schreef Jean-Michel Durand <
***@***.***>:

**Comment by OneGeekArmy** [comment]
Brilliant. I'd love to see what it looks like once it's formatted in your machine.Thanks!Le 11 févr. 2024 à 16:44, Benedict Thienpont ***@***.***> a écrit :﻿
Hi JM,



I will send you a 2GB image I created with Disk Jockey (Beta v3) using the

'Other' option.



Regards,

Benedict



Op za 27 jan 2024 om 13:56 schreef Jean-Michel Durand <

***@***.***>:

**Comment by OneGeekArmy** [comment]
This was added to Disk Jockey v3. Images now go up to 256 GB.
