### ISSUE TITLE
Allow user to select target volume for image creation

### ISSUE THREAD

**Issue by cgervais** [OneGeekArmy/Disk-Jockey-Community#13]
Creating an image currently defaults, on my machine, to ~/Downloads, but I'd prefer to choose a different target for saving the image.

One possible idiom to use is to detect if the Command key is held down when the user clicks on "Create the Image", update the button title to add an ellipsis, and then allow the user to choose a new target to save the image (or add Create Image in the File menu. Anyway, that's an implementation decision for you

**Comment by OneGeekArmy** [comment]
Good idea. I'll add it to the bucket list.

**Comment by OneGeekArmy** [comment]
This was added to Disk Jockey v3. You can change the destination folder in Settings.
