### ISSUE TITLE
DiscJockey 2.5.2 doesn't run on MacOS High Sierra (10.13.6)

### ISSUE THREAD

**Issue by Jack20947** [OneGeekArmy/Disk-Jockey-Community#15]
Just downloaded DiscJockey for Mac version 2.5.2.
It doesn't open, says macOS 10.14.6 is needed.

From website it seems it should work from 10.11 onward.

**Comment by OneGeekArmy** [comment]
Hi! Indeed, there was an issue with the compilation. You may want to download Disk Jockey again. It should work on Mac OS 11.13 and up.
