### ISSUE TITLE
Make Device Image crashes 3.0

### ISSUE THREAD

**Issue by opualuan** [OneGeekArmy/Disk-Jockey-Community#26]
Open HFS image, make device image causes v3.0 to quit. 2.5 works fine, converts and does not crash.

**Comment by OneGeekArmy** [comment]
Could you update to version 3.1.1 and see if the problem persists?

If it does, could you tell me the specs of your machine (macOS version and whether it's Intel or Apple Silicon) and eventually send the image my way?

Thanks

**Comment by opualuan** [comment]
This was done using 3.1.1 originally, this is the version that’s not working for me.

I’m using Sonoma 14.2.1 on M2 Apple Silicon. Tried again, and just like that, I can’t replicate the issue any longer!

**Comment by OneGeekArmy** [comment]
Closing it, then :)
