### ISSUE TITLE
Odd disk image that crashes Disk Jockey

### ISSUE THREAD

**Issue by mabinog1an** [OneGeekArmy/Disk-Jockey-Community#29]
Since you solved my last puzzle so readily, here's another for you:
The attached, nearly empty Mac disk image (an HFS Volume) is readily mountable and usable by SheepShaver and Mini-vMac. 
Yet attempting to view it with Disk-O-Matic (DOM) causes Disk Jockey (v3.3 Mac) to crash. 

My conjecture is that this is not so much a bug as an instance of DOM seeing and not handling gracefully some unexpected condition on this particular image. Apple's trusty old Disk First Aid program reports nothing amiss when it's mounted. But there still seems to be something subtly "off" about it.

[CrashesDJ.dsk.zip](https://github.com/user-attachments/files/15776286/CrashesDJ.dsk.zip)

**Comment by OneGeekArmy** [comment]
Thank you for this. Your example points to an issue in the way DOM is parsing the Extents Overflow file. It contains the location of all the various chunks of a file (when they get to a certain size) and this one seems a little problematic. It's a very interesting case and I'll take a look tomorrow.

Also, I'm getting ready to release a version around the end of this week with HFS+ support. You should no longer see the where_have_my_files_gone file :)

**Comment by OneGeekArmy** [comment]
I have localized and fixed the issue.
I should have a new version of DJ with HFS+ support and this bug fix (and a couple more niceties) out around the end of the week.
Thanks again for the report.

**Comment by mabinog1an** [comment]
Thanks. Just updated to version 3.4, and it does indeed heal both issues.  Nice work!

**Comment by OneGeekArmy** [comment]
Glad it's all solved! :)
