### ISSUE TITLE
Floppy capacity displays in MB

### ISSUE THREAD

**Issue by UpLateGeek** [OneGeekArmy/Disk-Jockey-Community#6]
Use classic configuration -> Other -> Floppy
Capacity displays MB next to drop-down, instead of KB.

Issue is only cosmetic: file name is correct and created file is correct.
![dj](https://user-images.githubusercontent.com/67256958/197320956-fb195040-881f-4916-ad97-ef17539fe8d4.png)

**Comment by OneGeekArmy** [comment]
Good eye! Thanks for reporting this. The bug has been found and squashed. The next version will behave as intended.
