### ISSUE TITLE
Include software updater

### ISSUE THREAD

**Issue by cgervais** [OneGeekArmy/Disk-Jockey-Community#7]
Considering integrating [Sparkle](https://sparkle-project.org) or something similar to make staying up-to-date easier

**Comment by OneGeekArmy** [comment]
Thanks for taking the time to submit a suggestion! I have great news for you: Disk Jockey includes the Sparkle framework since version 2.5! It's in the [release notes](https://diskjockey.onegeekarmy.eu/files/diskjockey/Disk-Jockey.app.html) but maybe I should mention that on the main page.

**Comment by cgervais** [comment]
Amazing! I dl'ed 2.5 and didn't even check it 🤦🏻‍♂️ Thanks for this terrific app!
