### ISSUE TITLE
Include the version number in the download filename again

### ISSUE THREAD

**Issue by ryandesign** [OneGeekArmy/Disk-Jockey-Community#9]
Please return to including the version number in the download filename. For example, you previously offered Disk-Jockey-v2.1.zip but now for 2.5 you offer Disk-Jockey.app.zip.

[DiskJockey can be installed using MacPorts](https://ports.macports.org/port/DiskJockey), a package management system. If MacPorts is currently offering DiskJockey 2.5 and the user asks to install DiskJockey with MacPorts, MacPorts may download Disk-Jockey.app.zip from your site. MacPorts is expecting to receive a file for a specific recorded version of the software which has specific recorded checksums. If MacPorts is expecting the file for 2.5 but you've replaced it with a different file of the same name that contains 2.6, MacPorts may prevent the user from installing the port because the checksums don't match and the user will be inconvenienced by needing to file a bug report and wait for it to be resolved before they can install the software. On the other hand, if you include the version number, you can freely add a new file for 2.6 while keeping the old file for 2.5. A user installing with MacPorts might then still download the 2.5 file, and in due time MacPorts will be updated to offer 2.6 instead, but at any time the user can install the port without error. Even if you delete the 2.5 file immediately when you publish 2.6 there is no problem for MacPorts since MacPorts servers mirror the old files.

**Comment by OneGeekArmy** [comment]
I will investigate how to put this in place without breaking the auto-update mechanism currently in place in Disk Jockey. Obviously, keeping the auto-update function is my primary goal but I'll try to see if it can be made to work with MacPorts too.

**Comment by OneGeekArmy** [comment]
This will not be possible without breaking the auto-update mechanism.
